# You may pin to the exact commit or the version.
  # uses: amondnet/vercel-action@16e87c0a08142b0d0d33b76aeaf20823c381b9b9
  name: My Workflow
  on:
    push:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Deploy to Vercel
          uses: amondnet/vercel-action@v25
          with:
            vercel-token: Yapy3wYhGDo7lKTsoYXYFahh
            github-comment: true
          
